# General user specific settings
#
# -------------------------------------------------------------------------------------------------
# set the color of username and hostname promted in terminal
# the username and hostname will look like 'user@hostname:~$' in your terminal session
export PS1='\[\e[0;33m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;34m\]\w\[\e[0m\]\$ '
export CLICOLOR=1
export LSCOLORS=gxfxaxdxcxegedabagacad

# -------------------------------------------------------------------------------------------------
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias ld='ls -l | grep "^d"' # List only directories
alias l='ls -CF'

# -------------------------------------------------------------------------------------------------
# set the vim alias to use other distribution vim (version 8.0), which supports '+clipboard'
alias vi='/usr/local/bin/vim'
alias vim='/usr/local/bin/vim'

# -------------------------------------------------------------------------------------------------
# JVM and JDK configuration
#
# Java 8 does not support "MaxPermSize" option, used to set JVM options launched by scala
export JAVA_OPTS="-Xms1024m -Xmx2048m"
# If scala is installed via 'brew install scala', it requires JAVA_HOME is set properly
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

# -------------------------------------------------------------------------------------------------
export PATH=$PATH:/usr/local/sbin  # macOS Sierra does not include `sbin` in PATH

# -------------------------------------------------------------------------------------------------
# Bash history file settings
export HISTFILESIZE=10000000
export HISTSIZE=10000000

# -------------------------------------------------------------------------------------------------
# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

